// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ServiceRequestSystem.Data;

#nullable disable

namespace ServiceRequestSystem.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260523203141_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ServiceRequestSystem.Models.Equipment", b =>
                {
                    b.Property<int>("EquipmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EquipmentId"));

                    b.Property<string>("EquipmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EquipmentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceObjectId")
                        .HasColumnType("int");

                    b.HasKey("EquipmentId");

                    b.HasIndex("ServiceObjectId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestComment", b =>
                {
                    b.Property<int>("RequestCommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestCommentId"));

                    b.Property<string>("CommentText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestCommentId");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestComments");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestHistory", b =>
                {
                    b.Property<int>("RequestHistoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestHistoryId"));

                    b.Property<string>("ActionType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("NewValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OldValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceRequestId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("RequestHistoryId");

                    b.HasIndex("ServiceRequestId");

                    b.HasIndex("UserId");

                    b.ToTable("RequestHistory");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestPriority", b =>
                {
                    b.Property<int>("RequestPriorityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestPriorityId"));

                    b.Property<string>("PriorityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestPriorityId");

                    b.ToTable("RequestPriorities");

                    b.HasData(
                        new
                        {
                            RequestPriorityId = 1,
                            PriorityName = "Низький"
                        },
                        new
                        {
                            RequestPriorityId = 2,
                            PriorityName = "Середній"
                        },
                        new
                        {
                            RequestPriorityId = 3,
                            PriorityName = "Високий"
                        },
                        new
                        {
                            RequestPriorityId = 4,
                            PriorityName = "Критичний"
                        });
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestStatus", b =>
                {
                    b.Property<int>("RequestStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RequestStatusId"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RequestStatusId");

                    b.ToTable("RequestStatuses");

                    b.HasData(
                        new
                        {
                            RequestStatusId = 1,
                            StatusName = "Нова"
                        },
                        new
                        {
                            RequestStatusId = 2,
                            StatusName = "Зареєстрована"
                        },
                        new
                        {
                            RequestStatusId = 3,
                            StatusName = "Призначена"
                        },
                        new
                        {
                            RequestStatusId = 4,
                            StatusName = "У роботі"
                        },
                        new
                        {
                            RequestStatusId = 5,
                            StatusName = "Очікує уточнення"
                        },
                        new
                        {
                            RequestStatusId = 6,
                            StatusName = "Виконана"
                        },
                        new
                        {
                            RequestStatusId = 7,
                            StatusName = "Закрита"
                        },
                        new
                        {
                            RequestStatusId = 8,
                            StatusName = "Скасована"
                        });
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            RoleName = "Клієнт"
                        },
                        new
                        {
                            RoleId = 2,
                            RoleName = "Оператор"
                        },
                        new
                        {
                            RoleId = 3,
                            RoleName = "Інженер"
                        },
                        new
                        {
                            RoleId = 4,
                            RoleName = "Адміністратор"
                        },
                        new
                        {
                            RoleId = 5,
                            RoleName = "Керівник"
                        });
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.ServiceObject", b =>
                {
                    b.Property<int>("ServiceObjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceObjectId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPerson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ObjectName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceObjectId");

                    b.ToTable("ServiceObjects");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.ServiceRequest", b =>
                {
                    b.Property<int>("ServiceRequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceRequestId"));

                    b.Property<int?>("AssignedEngineerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RequestPriorityId")
                        .HasColumnType("int");

                    b.Property<int>("RequestStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Result")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ServiceObjectId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("ServiceRequestId");

                    b.HasIndex("AssignedEngineerId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("RequestPriorityId");

                    b.HasIndex("RequestStatusId");

                    b.HasIndex("ServiceObjectId");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.Equipment", b =>
                {
                    b.HasOne("ServiceRequestSystem.Models.ServiceObject", "ServiceObject")
                        .WithMany("Equipment")
                        .HasForeignKey("ServiceObjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ServiceObject");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestComment", b =>
                {
                    b.HasOne("ServiceRequestSystem.Models.ServiceRequest", "ServiceRequest")
                        .WithMany("Comments")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceRequestSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestHistory", b =>
                {
                    b.HasOne("ServiceRequestSystem.Models.ServiceRequest", "ServiceRequest")
                        .WithMany("History")
                        .HasForeignKey("ServiceRequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ServiceRequestSystem.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ServiceRequest");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.ServiceRequest", b =>
                {
                    b.HasOne("ServiceRequestSystem.Models.User", "AssignedEngineer")
                        .WithMany()
                        .HasForeignKey("AssignedEngineerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("ServiceRequestSystem.Models.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceRequestSystem.Models.RequestPriority", "RequestPriority")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("RequestPriorityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceRequestSystem.Models.RequestStatus", "RequestStatus")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("RequestStatusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("ServiceRequestSystem.Models.ServiceObject", "ServiceObject")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("ServiceObjectId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedEngineer");

                    b.Navigation("CreatedByUser");

                    b.Navigation("RequestPriority");

                    b.Navigation("RequestStatus");

                    b.Navigation("ServiceObject");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.User", b =>
                {
                    b.HasOne("ServiceRequestSystem.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestPriority", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.RequestStatus", b =>
                {
                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.ServiceObject", b =>
                {
                    b.Navigation("Equipment");

                    b.Navigation("ServiceRequests");
                });

            modelBuilder.Entity("ServiceRequestSystem.Models.ServiceRequest", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("History");
                });
#pragma warning restore 612, 618
        }
    }
}
